language: android
install: ./gradlew :api:assemble :core:assemble :gateway:assemble
script:
  - ./gradlew :api:check :core:check :gateway:check sonarqube
android:
  components:
  - build-tools-28.0.3
  - android-28